<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="category_route_tests.py" name="category_route_tests.CategoryRouteTest-20200424152752" skipped="0" tests="2" time="0.003" timestamp="2020-04-24T15:27:52">
	<testcase classname="category_route_tests.CategoryRouteTest" file="src\unittest\python\category_route_tests.py" line="22" name="test_get_categories_with_none_in_database" time="0.002" timestamp="2020-04-24T15:27:52">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="category_route_tests.CategoryRouteTest" file="src\unittest\python\category_route_tests.py" line="30" name="test_get_products_with_one_in_database" time="0.001" timestamp="2020-04-24T15:27:52">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
