<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="product_route_tests.py" name="product_route_tests.ProductRouteTest-20200412171737" skipped="0" tests="2" time="0.008" timestamp="2020-04-12T17:17:37">
	<testcase classname="product_route_tests.ProductRouteTest" file="src\unittest\python\product_route_tests.py" line="30" name="test_get_products_with_none_in_database" time="0.005" timestamp="2020-04-12T17:17:37">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="product_route_tests.ProductRouteTest" file="src\unittest\python\product_route_tests.py" line="38" name="test_get_products_with_one_in_database" time="0.003" timestamp="2020-04-12T17:17:37">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
